const { Cat } = require("../components/cat/model");
const { Client } = require("../components/client/model");
const { User } = require("../components/user/model");
const { passwordGen } = require("./functions");

// CREATE USER FOR CHALLENGE
async function initChallenge() {
  await CreateUser();
  await CreateCatsStatus();
  await CreateListClients();
}

async function CreateUser() {
  const userValue = new User({
    createDate: new Date().toISOString(),
    name: "Felipe Freire",
    email: "recrutamento@sharenergy.com.br",
    networkLogin: "desafiosharenergy",
    password: "sh@r3n3rgy",
    birthDate: "1995-04-20",
  });
  await userValue.validate();

  const processedUser = passwordGen(userValue);

  const userFound = await User.findOne({
    $or: [
      { email: processedUser.email },
      { networkLogin: processedUser.networkLogin },
    ],
  });
  if (userFound) {
    return;
  }
  return await User.create(processedUser);
}
async function CreateCatsStatus() {
  const statusPreConfig = [
    {
      label: "Informativo 1**",
      status: [
        { status: 100, name: "Continue" },
        { status: 101, name: "Switching Protocols" },
        { status: 102, name: "Processing" },
        { status: 103, name: "Early Hints" },
      ],
    },
    {
      label: "Sucesso 2**",
      status: [
        { status: 200, name: "OK" },
        { status: 201, name: "Created" },
        { status: 202, name: "Accepted" },
        { status: 203, name: "Non-Authoritative Information" },
        { status: 204, name: "No Content" },
        { status: 206, name: "Partial Content" },
        { status: 207, name: "Multi-Status" },
      ],
    },
    {
      label: "Redirecionamento 3**",
      status: [
        { status: 300, name: "Multiple Choices" },
        { status: 301, name: "Moved Permanently" },
        { status: 302, name: "Found" },
        { status: 303, name: "See Other" },
        { status: 304, name: "Not Modified" },
        { status: 305, name: "Use Proxy" },
        { status: 307, name: "Temporary Redirect" },
        { status: 308, name: "Permanent Redirect" },
      ],
    },
    {
      label: "Erro do Client 4**",
      status: [
        { status: 400, name: "Bad Request" },
        { status: 401, name: "Unauthorized" },
        { status: 402, name: "Payment Required" },
        { status: 403, name: "Forbidden" },
        { status: 404, name: "Not Found" },
        { status: 405, name: "Method Not Allowed" },
        { status: 406, name: "Not Acceptable" },
        { status: 407, name: "Proxy Authentication Required" },
        { status: 408, name: "Request Timeout" },
        { status: 409, name: "Conflict" },
        { status: 410, name: "Gone" },
        { status: 411, name: "Length Required" },
        { status: 412, name: "Precondition Failed" },
        { status: 413, name: "Payload Too Large" },
        { status: 414, name: "Request-URI Too Long" },
        { status: 415, name: "Unsupported Media Type" },
        { status: 416, name: "Request Range Not Satisfiable" },
        { status: 417, name: "Expectation Failed" },
        { status: 418, name: "I’m a teapot" },
        { status: 420, name: "Enhance Your Calm" },
        { status: 421, name: "Misdirected Request" },
        { status: 422, name: "Unprocessable Entity" },
        { status: 423, name: "Locked" },
        { status: 424, name: "Failed Dependency" },
        { status: 425, name: "Too Early" },
        { status: 426, name: "Upgrade Required" },
        { status: 429, name: "Too Many Requests" },
        { status: 431, name: "Request Header Fields Too Large" },
        { status: 444, name: "No Response" },
        { status: 450, name: "Blocked by Windows Parental Controls" },
        { status: 451, name: "Unavailable For Legal Reasons" },
        { status: 497, name: "HTTP Request Sent to HTTPS Port" },
        { status: 498, name: "Token expired/invalid" },
        { status: 499, name: "Client Closed Request" },
      ],
    },
    {
      label: "Erro do Servidor 5**",
      status: [
        { status: 500, name: "Internal Server Error" },
        { status: 501, name: "Not Implemented" },
        { status: 502, name: "Bad Gateway" },
        { status: 503, name: "Service Unavailable" },
        { status: 504, name: "Gateway Timeout" },
        { status: 506, name: "Variant Also Negotiates" },
        { status: 507, name: "Insufficient Storage" },
        { status: 508, name: "Loop Detected" },
        { status: 509, name: "Bandwidth Limit Exceeded" },
        { status: 510, name: "Not Extended" },
        { status: 511, name: "Network Authentication Required" },
        { status: 521, name: "Web Server Is Down" },
        { status: 522, name: "Connection Timed Out" },
        { status: 523, name: "Origin Is Unreachable" },
        { status: 525, name: "SSL Handshake Failed" },
        { status: 599, name: "Network Connect Timeout Error" },
      ],
    },
  ];

  for (group of statusPreConfig) {
    const found = await Cat.findOne({
      $or: [{ label: group.label }],
    });
    if (!found) {
      await Cat.create(group);
    }
  }
}

async function CreateListClients() {
  const clients = [
    {
      number: 780,
      cell: "(34) 9366-7368",
      city: "Santo André",
      district: "",
      cpf: "70100293087",
      email: "aimee.lima@example.com",
      name: "Aimée Lima",
      phone: "(91) 5346-2945",
      state: "Goiás",
      street: "Rua Castro Alves ",
      picture: "https://randomuser.me/api/portraits/women/84.jpg",
    },
    {
      number: 3536,
      cell: "(66) 1796-7942",
      city: "Itapecerica da Serra",
      district: "",
      cpf: "72760424027",
      email: "mago.moreira@example.com",
      name: "Mago Moreira",
      phone: "(76) 1066-3704",
      state: "Mato Grosso do Sul",
      street: "Rua São Jorge ",
      picture: "https://randomuser.me/api/portraits/men/52.jpg",
    },
    {
      number: 980,
      cell: "(00) 6322-6523",
      city: "Rio Verde",
      district: "",
      cpf: "66922792160",
      email: "felisberta.sales@example.com",
      name: "Felisberta Sales",
      phone: "(56) 2557-1965",
      state: "Roraima",
      street: "Rua Onze ",
      picture: "https://randomuser.me/api/portraits/women/16.jpg",
    },
    {
      number: 4153,
      cell: "(31) 3822-3773",
      city: "Belém",
      district: "",
      cpf: "23832048747",
      email: "dania.barros@example.com",
      name: "Dânia Barros",
      phone: "(27) 2532-6543",
      state: "Amapá",
      street: "Rua Carlos Gomes",
      picture: "https://randomuser.me/api/portraits/women/44.jpg",
    },
    {
      number: 235,
      cell: "(99) 3894-2414",
      city: "Itajaí",
      district: "",
      cpf: "36648220934",
      email: "joao.lima@example.com",
      name: "João Lima",
      phone: "(44) 0118-0788",
      state: "Ceará",
      street: "Rua Piauí ",
      picture: "https://randomuser.me/api/portraits/men/79.jpg",
    },
    {
      number: 3794,
      cell: "(45) 7675-7939",
      city: "Canoas",
      district: "",
      cpf: "85296575812",
      email: "nivaldo.santos@example.com",
      name: "Nivaldo Santos",
      phone: "(56) 7203-3270",
      state: "Pará",
      street: "Rua Treze ",
      picture: "https://randomuser.me/api/portraits/men/80.jpg",
    },
    {
      number: 7109,
      cell: "(10) 1675-9639",
      city: "Votorantim",
      district: "",
      cpf: "07926161717",
      email: "maricilda.pinto@example.com",
      name: "Maricilda Pinto",
      phone: "(04) 9277-4051",
      state: "Paraná",
      street: "Rua Santa Rita ",
      picture: "https://randomuser.me/api/portraits/women/39.jpg",
    },
    {
      number: 599,
      cell: "(28) 4256-9179",
      city: "Guarulhos",
      district: "",
      cpf: "84473544234",
      email: "simauro.damata@example.com",
      name: "Simauro da Mata",
      phone: "(18) 8489-4371",
      state: "São Paulo",
      street: "Travessa dos Martírios",
      picture: "https://randomuser.me/api/portraits/men/94.jpg",
    },
    {
      number: 605,
      cell: "(31) 5365-0159",
      city: "Betim",
      district: "",
      cpf: "90154269689",
      email: "ximena.goncalves@example.com",
      name: "Ximena Gonçalves",
      phone: "(58) 5385-9211",
      state: "Piauí",
      street: "Rua Pará ",
      picture: "https://randomuser.me/api/portraits/women/81.jpg",
    },
    {
      number: 1845,
      cell: "(39) 9889-5933",
      city: "Maringá",
      district: "",
      cpf: "64969859539",
      email: "eloides.moraes@example.com",
      name: "Elóides Moraes",
      phone: "(79) 1735-7389",
      state: "Acre",
      street: "Rua Rui Barbosa ",
      picture: "https://randomuser.me/api/portraits/women/24.jpg",
    },
    {
      number: 1133,
      cell: "(69) 1037-5021",
      city: "Itaquaquecetuba",
      district: "",
      cpf: "95262928837",
      email: "antonia.novaes@example.com",
      name: "Antônia Novaes",
      phone: "(71) 1369-2026",
      state: "Pará",
      street: "Rua Sete de Setembro ",
      picture: "https://randomuser.me/api/portraits/women/75.jpg",
    },
    {
      number: 6710,
      cell: "(04) 8115-3281",
      city: "Santa Cruz do Sul",
      district: "",
      cpf: "45558991267",
      email: "eveline.silva@example.com",
      name: "Eveline Silva",
      phone: "(52) 7878-0630",
      state: "Minas Gerais",
      street: "Rua João Xxiii",
      picture: "https://randomuser.me/api/portraits/women/56.jpg",
    },
    {
      number: 4073,
      cell: "(70) 3678-5660",
      city: "Porto Seguro",
      district: "",
      cpf: "38019457917",
      email: "giulia.caldeira@example.com",
      name: "Giulia Caldeira",
      phone: "(96) 2626-0431",
      state: "Ceará",
      street: "Rua Quatro",
      picture: "https://randomuser.me/api/portraits/women/12.jpg",
    },
    {
      number: 7270,
      cell: "(11) 7701-2587",
      city: "Catanduva",
      district: "",
      cpf: "60688991829",
      email: "durbalino.monteiro@example.com",
      name: "Durbalino Monteiro",
      phone: "(51) 7673-4096",
      state: "Distrito Federal",
      street: "Rua Boa Vista ",
      picture: "https://randomuser.me/api/portraits/men/31.jpg",
    },
    {
      number: 9506,
      cell: "(40) 9204-2008",
      city: "Diadema",
      district: "",
      cpf: "04044323425",
      email: "adelmiro.sales@example.com",
      name: "Adelmiro Sales",
      phone: "(97) 6971-8312",
      state: "Piauí",
      street: "Rua Santo Antônio ",
      picture: "https://randomuser.me/api/portraits/men/28.jpg",
    },
    {
      number: 7624,
      cell: "(90) 7462-9034",
      city: "Rio Verde",
      district: "",
      cpf: "26131356591",
      email: "clesisniara.ferreira@example.com",
      name: "Clesisniara Ferreira",
      phone: "(14) 3907-8279",
      state: "Mato Grosso do Sul",
      street: "Travessa dos Açorianos",
      picture: "https://randomuser.me/api/portraits/women/21.jpg",
    },
    {
      number: 748,
      cell: "(15) 5258-9609",
      city: "Passo Fundo",
      district: "",
      cpf: "15386215701",
      email: "maeve.alves@example.com",
      name: "Maeve Alves",
      phone: "(68) 3049-0531",
      state: "Roraima",
      street: "Rua Das Flores ",
      picture: "https://randomuser.me/api/portraits/women/52.jpg",
    },
    {
      number: 133,
      cell: "(34) 2173-1764",
      city: "Brasília",
      district: "",
      cpf: "88607716577",
      email: "benta.teixeira@example.com",
      name: "Benta Teixeira",
      phone: "(86) 4631-1554",
      state: "Santa Catarina",
      street: "Rua Santa Catarina ",
      picture: "https://randomuser.me/api/portraits/women/45.jpg",
    },
    {
      number: 3334,
      cell: "(73) 3481-4023",
      city: "Americana",
      district: "",
      cpf: "73297802684",
      email: "flora.ribeiro@example.com",
      name: "Flora Ribeiro",
      phone: "(13) 6273-8291",
      state: "Rio Grande do Norte",
      street: "Rua Paraíba ",
      picture: "https://randomuser.me/api/portraits/women/8.jpg",
    },
    {
      number: 2471,
      cell: "(50) 9813-8609",
      city: "Belém",
      district: "",
      cpf: "09940887214",
      email: "salustiniano.mendes@example.com",
      name: "Salustiniano Mendes",
      phone: "(61) 6122-8272",
      state: "Acre",
      street: "Rua Doze ",
      picture: "https://randomuser.me/api/portraits/men/86.jpg",
    },
    {
      number: 4617,
      cell: "(77) 5782-6709",
      city: "São José dos Pinhais",
      district: "",
      cpf: "00794145406",
      email: "indra.dacosta@example.com",
      name: "Indra da Costa",
      phone: "(20) 6042-5889",
      state: "Ceará",
      street: "Rua Tiradentes ",
      picture: "https://randomuser.me/api/portraits/men/55.jpg",
    },
    {
      number: 1844,
      cell: "(68) 9709-8733",
      city: "Juiz de Fora",
      district: "",
      cpf: "41401345767",
      email: "falcao.lopes@example.com",
      name: "Falcão Lopes",
      phone: "(22) 4777-6516",
      state: "Rio Grande do Norte",
      street: "Rua Carlos Gomes",
      picture: "https://randomuser.me/api/portraits/men/59.jpg",
    },
    {
      number: 1028,
      cell: "(96) 9510-3942",
      city: "Guarujá",
      district: "",
      cpf: "10253435394",
      email: "herberto.caldeira@example.com",
      name: "Herberto Caldeira",
      phone: "(31) 0673-2865",
      state: "Alagoas",
      street: "Rua Dezesseis de Maio",
      picture: "https://randomuser.me/api/portraits/men/1.jpg",
    },
    {
      number: 4471,
      cell: "(61) 2107-0748",
      city: "Sinop",
      district: "",
      cpf: "14624970513",
      email: "jucineide.damota@example.com",
      name: "Jucineide da Mota",
      phone: "(45) 2818-5537",
      state: "Sergipe",
      street: "Rua Dezenove de Outubro",
      picture: "https://randomuser.me/api/portraits/women/56.jpg",
    },
    {
      number: 7839,
      cell: "(95) 3374-7889",
      city: "Apucarana",
      district: "",
      cpf: "06518547088",
      email: "diovalda.martins@example.com",
      name: "Diovalda Martins",
      phone: "(59) 1546-7027",
      state: "Pará",
      street: "Rua Espirito Santo ",
      picture: "https://randomuser.me/api/portraits/women/6.jpg",
    },
    {
      number: 9683,
      cell: "(81) 7371-2283",
      city: "Ibirité",
      district: "",
      cpf: "07503786856",
      email: "josiele.darocha@example.com",
      name: "Josiele da Rocha",
      phone: "(66) 4563-7345",
      state: "Minas Gerais",
      street: "Rua São João ",
      picture: "https://randomuser.me/api/portraits/women/18.jpg",
    },
    {
      number: 9800,
      cell: "(40) 5697-7255",
      city: "Recife",
      district: "",
      cpf: "26656293920",
      email: "isac.silveira@example.com",
      name: "Isac Silveira",
      phone: "(07) 0334-4944",
      state: "Goiás",
      street: "Avenida da Legalidade",
      picture: "https://randomuser.me/api/portraits/men/87.jpg",
    },
    {
      number: 5350,
      cell: "(02) 8685-0528",
      city: "Recife",
      district: "",
      cpf: "40325011416",
      email: "habacuque.peixoto@example.com",
      name: "Habacuque Peixoto",
      phone: "(77) 2945-7135",
      state: "Alagoas",
      street: "Rua da Paz ",
      picture: "https://randomuser.me/api/portraits/men/6.jpg",
    },
    {
      number: 8341,
      cell: "(58) 7104-3100",
      city: "São Luís",
      district: "",
      cpf: "60987006544",
      email: "lida.moraes@example.com",
      name: "Lida Moraes",
      phone: "(03) 1930-4036",
      state: "Paraíba",
      street: "Rua Treze ",
      picture: "https://randomuser.me/api/portraits/women/91.jpg",
    },
    {
      number: 4539,
      cell: "(80) 5311-1660",
      city: "Teresópolis",
      district: "",
      cpf: "04131677242",
      email: "macario.barbosa@example.com",
      name: "Macário Barbosa",
      phone: "(18) 8722-0245",
      state: "Rio de Janeiro",
      street: "Rua Bela Vista ",
      picture: "https://randomuser.me/api/portraits/men/83.jpg",
    },
    {
      number: 8204,
      cell: "(58) 4491-3570",
      city: "Cabo de Santo Agostinho",
      district: "",
      cpf: "71836659551",
      email: "elisio.daluz@example.com",
      name: "Elísio da Luz",
      phone: "(50) 2840-6822",
      state: "Maranhão",
      street: "Rua Paraná ",
      picture: "https://randomuser.me/api/portraits/men/78.jpg",
    },
    {
      number: 311,
      cell: "(38) 7854-5816",
      city: "Juazeiro",
      district: "",
      cpf: "61253729050",
      email: "zelaci.duarte@example.com",
      name: "Zelaci Duarte",
      phone: "(43) 7264-9276",
      state: "Maranhão",
      street: "Rua Dezessete ",
      picture: "https://randomuser.me/api/portraits/women/36.jpg",
    },
    {
      number: 1540,
      cell: "(89) 0909-1663",
      city: "Camaçari",
      district: "",
      cpf: "28236392394",
      email: "zoneide.darosa@example.com",
      name: "Zoneide da Rosa",
      phone: "(33) 4626-3739",
      state: "Pará",
      street: "Rua Dezenove de Outubro",
      picture: "https://randomuser.me/api/portraits/women/10.jpg",
    },
    {
      number: 7973,
      cell: "(65) 4067-0579",
      city: "Ibirité",
      district: "",
      cpf: "24266134915",
      email: "andre.ramos@example.com",
      name: "André Ramos",
      phone: "(32) 1927-4626",
      state: "Ceará",
      street: "Avenida D. Pedro Ii",
      picture: "https://randomuser.me/api/portraits/men/93.jpg",
    },
    {
      number: 7214,
      cell: "(08) 9890-3783",
      city: "Barueri",
      district: "",
      cpf: "26986928682",
      email: "iridea.rezende@example.com",
      name: "Irídea Rezende",
      phone: "(63) 0699-5778",
      state: "Sergipe",
      street: "Rua Tiradentes ",
      picture: "https://randomuser.me/api/portraits/women/30.jpg",
    },
    {
      number: 8155,
      cell: "(79) 2325-6527",
      city: "Mauá",
      district: "",
      cpf: "27949499716",
      email: "silviana.dasneves@example.com",
      name: "Silviana das Neves",
      phone: "(65) 7262-0500",
      state: "Alagoas",
      street: "Avenida da Legalidade",
      picture: "https://randomuser.me/api/portraits/women/26.jpg",
    },
    {
      number: 7631,
      cell: "(18) 0282-5980",
      city: "Ponta Grossa",
      district: "",
      cpf: "02473612465",
      email: "tamires.martins@example.com",
      name: "Tamires Martins",
      phone: "(14) 4796-6534",
      state: "Ceará",
      street: "Rua Rio de Janeiro ",
      picture: "https://randomuser.me/api/portraits/women/62.jpg",
    },
    {
      number: 370,
      cell: "(09) 4780-3187",
      city: "Araguari",
      district: "",
      cpf: "40615181663",
      email: "elisangela.viana@example.com",
      name: "Elisângela Viana",
      phone: "(79) 1294-2000",
      state: "Paraná",
      street: "Rua Onze ",
      picture: "https://randomuser.me/api/portraits/women/14.jpg",
    },
    {
      number: 4600,
      cell: "(86) 5019-7203",
      city: "Salvador",
      district: "",
      cpf: "48029276548",
      email: "carsta.moura@example.com",
      name: "Carsta Moura",
      phone: "(43) 3457-7360",
      state: "Santa Catarina",
      street: "Rua Quinze de Novembro ",
      picture: "https://randomuser.me/api/portraits/men/41.jpg",
    },
    {
      number: 5240,
      cell: "(82) 4573-8840",
      city: "Várzea Grande",
      district: "",
      cpf: "19561943665",
      email: "valter.moura@example.com",
      name: "Válter Moura",
      phone: "(77) 6338-1572",
      state: "Piauí",
      street: "Rua Espirito Santo ",
      picture: "https://randomuser.me/api/portraits/men/27.jpg",
    },
  ];
  for (client of clients) {
    const found = await Client.findOne(client);
    if (!found) {
      await Client.create(client);
    }
  }
}

module.exports = { initChallenge };
